"""Repositories package."""

from app.repositories.auth_repo import (
    PasswordHistoryRepository,
    PasswordResetRepository,
    PermissionRepository,
    RolePermissionRepository,
    RoleRepository,
    SessionRepository,
    UserRepository,
)
from app.repositories.base import BaseRepository
from app.repositories.catalog_repo import (
    BusinessInfoRepository,
    CategoryRepository,
    CurrencyRepository,
    ProductImageRepository,
    ProductRepository,
    SupplierContactRepository,
    SupplierHistoryRepository,
    SupplierRepository,
    TaxRateRepository,
)
from app.repositories.ops_repo import (
    CreditPaymentRepository,
    CreditSaleRepository,
    CustomerRepository,
    InventoryRepository,
    InventoryTransactionRepository,
    LowStockAlertRepository,
    PaymentMethodRepository,
    PaymentRepository,
    ReceiptRepository,
    ReturnItemRepository,
    ReturnReasonRepository,
    ReturnRepository,
    SaleItemRepository,
    SaleRepository,
    StockReconciliationRepository,
)
from app.repositories.system_repo import (
    ActivityLogRepository,
    AuditLogRepository,
    ErrorLogRepository,
    NotificationHistoryRepository,
    NotificationRepository,
    NotificationTypeRepository,
    SecurityLogRepository,
    SettingRepository,
    UserSettingRepository,
)

__all__ = [
    "ActivityLogRepository",
    "AuditLogRepository",
    "BaseRepository",
    "BusinessInfoRepository",
    "CategoryRepository",
    "CreditPaymentRepository",
    "CreditSaleRepository",
    "CurrencyRepository",
    "CustomerRepository",
    "ErrorLogRepository",
    "InventoryRepository",
    "InventoryTransactionRepository",
    "LowStockAlertRepository",
    "NotificationHistoryRepository",
    "NotificationRepository",
    "NotificationTypeRepository",
    "PasswordHistoryRepository",
    "PasswordResetRepository",
    "PaymentMethodRepository",
    "PaymentRepository",
    "PermissionRepository",
    "ProductImageRepository",
    "ProductRepository",
    "ReceiptRepository",
    "ReturnItemRepository",
    "ReturnReasonRepository",
    "ReturnRepository",
    "RolePermissionRepository",
    "RoleRepository",
    "SaleItemRepository",
    "SaleRepository",
    "SecurityLogRepository",
    "SessionRepository",
    "SettingRepository",
    "StockReconciliationRepository",
    "SupplierContactRepository",
    "SupplierHistoryRepository",
    "SupplierRepository",
    "TaxRateRepository",
    "UserRepository",
    "UserSettingRepository",
]
